---
name: CI
on:
  pull_request:
  push:
    branches: [main, development]
  workflow_dispatch: {}
jobs:
  test-smoke-action-gate-token:
    name: test the token passing
    uses: ./.github/workflows/smoke-action-gate-token.yaml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_ADMIN: ${{ secrets.CI_ADMIN }}
