---
name: Set Development Branch Protection
on:
  push:
    branches:
      - development
  workflow_dispatch:
jobs:
  set-development-branch-protection:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Apply Protection to development
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |-
          BRANCH="development"

          STATUS_CHECKS_JSON=$(jq -n '{
            strict: false,
            contexts: ["test-import-tracker"]
          }')

          PR_REVIEWS_JSON=$(jq -n '{
            required_approving_review_count: 1,
            dismiss_stale_reviews: false,
            require_code_owner_reviews: false,
            require_last_push_approval: false
          }')

          RESTRICTIONS=null
          ENFORCE_ADMINS=false
          ALLOW_FORCE_PUSHES=true
          ALLOW_DELETIONS=true
          LINEAR_HISTORY=false

          BRANCH_PROTECTION_PAYLOAD=$(jq -n \
            --argjson status_checks "$STATUS_CHECKS_JSON" \
            --argjson reviews "$PR_REVIEWS_JSON" \
            --argjson restrictions "$RESTRICTIONS" \
            --arg enforce_admins "$ENFORCE_ADMINS" \
            --arg allow_force_pushes "$ALLOW_FORCE_PUSHES" \
            --arg allow_deletions "$ALLOW_DELETIONS" \
            --arg required_linear_history "$LINEAR_HISTORY" \
            '{
              required_status_checks: $status_checks,
              enforce_admins: ($enforce_admins | test("true")),
              required_pull_request_reviews: $reviews,
              restrictions: $restrictions,
              allow_force_pushes: ($allow_force_pushes | test("true")),
              allow_deletions: ($allow_deletions | test("true")),
              required_linear_history: ($required_linear_history | test("true"))
            }'
          )

          echo "$BRANCH_PROTECTION_PAYLOAD" > payload.json

          echo "Setting protection on ${BRANCH}"
          gh api --method PUT \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/branches/${BRANCH}/protection" \
            --input payload.json
