---
name: fetch-ruleset-id
"on":
  workflow_call:
    inputs:
      ruleset_name:
        description: "The ruleset_name output via load-json/action.yml"
        required: true
        type: string
    outputs:
      ruleset_id:
        description: 'The ID of the found ruleset (or empty if not found)'
        value: ${{ jobs.fetch-ruleset-id.outputs.ruleset_id }}
    secrets:
      GH_TOKEN:
        required: true
jobs:
  fetch-ruleset-id:
    runs-on: ubuntu-latest
    outputs:
      ruleset_id: ${{ steps.fetch.outputs.result }}
    steps:
      - name: Fetch and extract ruleset ID
        id: fetch
        uses: ./.github/actions/github-rest-api
        with:
          method: GET
          endpoint: /repos/${{ github.repository }}/rulesets
          token: ${{ secrets.GH_TOKEN }}
          extract: '.[] | select(.name == \"${{ inputs.ruleset_name }}\") | .id'
      - id: validate
        if: ${{ ! steps.fetch.outputs.result }}
        run: |-
          echo "Empty ID result"
          echo "returned ruleset_id = ${{ steps.fetch.outputs.result }}"
          exit 1
