---
# .github/workflows/find-ruleset.yaml
name: find-ruleset
on:
  workflow_call:
    inputs:
      ruleset_name:
        description: 'The exact name of the ruleset to look up'
        required: true
        type: string
    outputs:
      ruleset_id:
        description: 'The ID of the found ruleset (or empty if not found)'
        value: ${{ jobs.lookup.outputs.ruleset_id }}
jobs:
  lookup:
    runs-on: ubuntu-latest
    outputs:
      ruleset_id: ${{ steps.find.outputs.id }}
    steps:
      - name: Lookup ruleset by name
        id: find
        run: |-
          id=$(gh api /repos/${{ github.repository }}/rulesets \
            --jq ".[] | select(.name==\"${{ inputs.ruleset_name }}\") | .id")
          echo "id=$id" >> "$GITHUB_OUTPUT"
