---
name: find-ruleset
"on":
  workflow_call:
    inputs:
      ruleset_name:
        description: 'The exact name of the ruleset to look up'
        required: true
        type: string
    outputs:
      ruleset_id:
        description: 'The ID of the found ruleset (or empty if not found)'
        value: ${{ jobs.lookup.outputs.ruleset_id }}
    secrets:
      GH_TOKEN:
        required: true
jobs:
  lookup:
    runs-on: ubuntu-latest
    outputs:
      ruleset_id: ${{ steps.extract.outputs.ruleset_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all rulesets
        id: fetch
        uses: ./.github/actions/github-rest-api
        with:
          method: GET
          endpoint: /repos/${{ github.repository }}/rulesets
          token: ${{ secrets.GH_TOKEN }}
      - name: Extract ruleset ID by name
        id: extract
        shell: bash
        run: |-
          echo '${{ steps.fetch.outputs.response }}' | \
            jq -r --arg name "${{ inputs.ruleset_name }}" \
              '.[] | select(.name == $name) | .id' > id.txt
          echo "ruleset_id=$(cat id.txt)" >> "$GITHUB_OUTPUT"
