---
# .github/workflows/release-please.yaml
name: release-please
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: utils-repl
          bump-minor-pre-major: true
          pull-request-title-pattern: "chore: release ${version}"
          changelog-types: |-
            [
              {"type": "feat", "section": "Features", "hidden": false},
              {"type": "fix", "section": "Bug Fixes", "hidden": false},
              {"type": "docs", "section": "Documentation", "hidden": true},
              {"type": "chore", "section": "Chores", "hidden": true}
            ]
