---
# .github/workflows/smoke-core-reset-smoke-repo.yaml
name: Smoke Test Reset Smoke Repo
on:
  workflow_dispatch:
    inputs:
      src_repo:
        required: true
        type: string
        default: robert-portelli/utils-repl
      dst_repo:
        required: true
        type: string
        default: robert-portelli/smoke-utils-repl
jobs:
  dst-reset:
    name: Start the smoke repo from a known state
    uses: ./.github/workflows/core-reset-smoke-repo.yaml
    with:
      src_repo: ${{ inputs.SRC_REPO }}
      dst_repo: ${{ inputs.DST_REPO }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_ADMIN: ${{ secrets.CI_ADMIN }}
  test-reset:
    name: Mutate dst_repo, reset the dst_repo, check for mutation
    runs-on: ubuntu-latest
    needs: dst-reset
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.DST_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: smoke-repo
      - name: Make a change and commit it
        working-directory: smoke-repo
        run: |
          echo "This should be wiped" > SMOKE_MUTATION.txt
          git config user.name "Smoke Tester"
          git config user.email "smoke@example.com"
          git add SMOKE_MUTATION.txt
          git commit -m "smoke: mutate repo with dummy file"
          git push origin HEAD
      - name: Confirm mutation exists
        working-directory: smoke-repo
        run: |
          test -f SMOKE_MUTATION.txt
          grep "This should be wiped" SMOKE_MUTATION.txt
  call-reset:
    name: Call Reset Workflow
    uses: ./.github/workflows/core-reset-smoke-repo.yaml
    needs: test-reset
    with:
      src_repo: ${{ inputs.SRC_REPO }}
      dst_repo: ${{ inputs.DST_REPO }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_ADMIN: ${{ secrets.CI_ADMIN }}
  verify-reset:
    name: Confirm repo was reset
    needs: call-reset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout smoke repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.SRC_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: smoke-repo
      - name: Assert that mutation is gone
        working-directory: smoke-repo
        run: |-
          if [[ -f SMOKE_MUTATION.txt ]]; then
            echo "❌ Reset failed: SMOKE_MUTATION.txt still exists"
            exit 1
          else
            echo "✅ Reset successful: SMOKE_MUTATION.txt is gone"
          fi
  check-rulesets:
    name: Check if branch rulesets are enabled
    needs: verify-reset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruleset:
          - path: ./smoke-repo/.github/rulesets/branch-default.json
          - path: ./smoke-repo/.github/rulesets/branch-release.json
          - path: ./smoke-repo/.github/rulesets/branch-development.json
          - path: ./smoke-repo/.github/rulesets/branch-feature.json
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.dst_repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: smoke-repo
      - name: "Load JSON: ruleset = ${{ matrix.ruleset.path }}"
        id: load-json
        uses: ./smoke-repo/.github/actions/load-json
        with:
          path: ${{ matrix.ruleset.path }}
      - name: "Query GitHub REST API for ruleset ${{ matrix.ruleset.path }}"
        id: query
        uses: ./smoke-repo/.github/actions/github-rest-api
        with:
          endpoint: /repos/robert-portelli/smoke-utils-repl/rulesets/${{ steps.load-json.outputs.ruleset_name
            }}
          method: GET
          token: ${{ secrets.GITHUB_TOKEN }}
          extract: '.enforcement'
          expected: 'active'
          retries: 3
          delay: 5
