---
name: Smoke Test Default Branch Ruleset Workflow
on:
  workflow_dispatch:  # calling the smoke test directly
    inputs:
      ruleset_path:
        description: "the path to the ruleset json"
        required: true
        type: string
        default: "./.github/rulesets/branch-default.json"
jobs:
  upsert-ruleset:
    name: Upsert Default Branch Ruleset
    uses: ./.github/workflows/upsert-ruleset-default-branch.yaml
    with:
      ruleset_path: ${{ inputs.ruleset_path }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_ADMIN: ${{ secrets.CI_ADMIN }}
