---
name: Smoke Test Fetch Ruleset ID
on:
  workflow_dispatch:
jobs:
  create-toy-ruleset:
    name: Create Toy Ruleset
    runs-on: ubuntu-latest
    outputs:
      extracted_id: ${{ steps.post.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: load the toy ruleset json
        id: load
        uses: ./.github/actions/load-json
        with:
          path: ./.github/rulesets/toy-ruleset.json
      - name: post the toy ruleset to the repo and extract the ruleset id for comparison
        id: post
        uses: ./.github/actions/github-rest-api
        with:
          method: POST
          endpoint: /repos/${{ github.repository }}/rulesets
          token: ${{ secrets.CI_ADMIN }}
          json_body: ${{ steps.load.outputs.json }}
          extract: '.id'
      - name: validate-result
        if: ${{ ! steps.post.outputs.result }}
        run: |-
          echo "Failed to extract ruleset_id during ruleset post"
          exit 1
  fetch-ruleset-id:
    name: Call fetch-ruleset-id.yaml
    needs: create-toy-ruleset
    uses: ./.github/workflows/fetch-ruleset-id.yaml
    with:
      ruleset_path: ./.github/rulesets/toy-ruleset.json
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  smoke-test:
    name: Compare created ID and fetched ID
    runs-on: ubuntu-latest
    needs: [create-toy-ruleset, fetch-ruleset-id]
    steps:
      - name: compare extracted ruleset_id with the fetched ruleset_id
        if: ${{ needs.create-toy-ruleset.outputs.extracted_id != needs.fetch-ruleset-id.outputs.ruleset_id
          }}
        run: |-
          echo "❌ Mismatch between created and fetched ruleset IDs"
          echo "🔍 Created ID: ${{ needs.create-toy-ruleset.outputs.extracted_id }}"
          echo "🔍 Fetched ID: ${{ needs.fetch-ruleset-id.outputs.ruleset_id }}"
          exit 1
  clean-up:
    name: Cleanup toy ruleset
    needs: [create-toy-ruleset, fetch-ruleset-id, smoke-test]
    runs-on: ubuntu-latest
    if: ${{ always() && needs.create-toy-ruleset.outputs.extracted_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Clean up toy ruleset
        uses: ./.github/actions/github-rest-api
        with:
          method: DELETE
          endpoint: /repos/${{ github.repository }}/rulesets/${{ needs.create-toy-ruleset.outputs.extracted_id
            }}
          token: ${{ secrets.CI_ADMIN }}
