---
name: Smoke Test Gate Admin
on:
  workflow_dispatch:
jobs:
  smoke-admin-check:
    name: Smoke Test admin-check workflow
    uses: ./.github/workflows/gate-admin.yaml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
