---
name: Smoke Test Find Ruleset
on:
  workflow_dispatch:
jobs:
  create-toy-ruleset:
    name: Create the toy ruleset
    runs-on: ubuntu-latest
    outputs:
      ruleset_name: toy-ruleset
      result: ${{ steps.post.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - id: create
        run: |-
          {
            echo 'json<<EOF'
            cat .github/rulesets/toy-ruleset.json
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - id: post
        uses: ./.github/actions/github-rest-api
        with:
          method: POST
          endpoint: /repos/${{ github.repository }}/rulesets
          json_body: ${{ steps.create.outputs.json }}
          extract: '.id'
          token: ${{ secrets.CI_ADMIN }}
  find-by-name:
    needs: create-toy-ruleset
    uses: ./.github/workflows/find-ruleset.yaml
    with:
      ruleset_name: ${{ needs.create-toy-ruleset.outputs.ruleset_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  find-by-json:
    needs: create-toy-ruleset
    uses: ./.github/workflows/find-ruleset.yaml
    with:
      json: .github/rulesets/toy-ruleset.json
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  validate-results:
    runs-on: ubuntu-latest
    needs: [create-toy-ruleset, find-by-name, find-by-json]
    steps:
      - name: 🧪 Compare created ID with both find results
        shell: bash
        run: |
          CREATED="${{ needs.create-toy-ruleset.outputs.result }}"
          BY_NAME="${{ needs.find-by-name.outputs.ruleset_id }}"
          BY_JSON="${{ needs.find-by-json.outputs.ruleset_id }}"

          echo "Created ID:  $CREATED"
          echo "Found by name: $BY_NAME"
          echo "Found by JSON: $BY_JSON"

          if [[ "$CREATED" != "$BY_NAME" ]]; then
            echo "❌ Mismatch with find-by-name"
            exit 1
          fi

          if [[ "$CREATED" != "$BY_JSON" ]]; then
            echo "❌ Mismatch with find-by-json"
            exit 1
          fi

          echo "✅ Ruleset ID matches for both name and JSON input"
  clean-up:
    name: 🧹 Delete toy ruleset
    runs-on: ubuntu-latest
    needs: [create-toy-ruleset, find-by-name, find-by-json, validate-results]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/github-rest-api
        with:
          method: DELETE
          endpoint: /repos/${{ github.repository }}/rulesets/${{ needs.create-toy-ruleset.outputs.result
            }}
          token: ${{ secrets.CI_ADMIN }}
