---
name: Smoke Test Load JSON (Matrix)
on:
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  run-matrix:
    strategy:
      matrix:
        test_case:
          - id: pretty
            compact: false
            smoke: false
            expected_name: toy-ruleset
            expected_ref: refs/heads/toy-branch
          - id: smoked
            compact: false
            smoke: true
            expected_name: smoke-toy-ruleset
            expected_ref: refs/heads/smoke-toy-branch
          - id: compact
            compact: true
            smoke: false
    name: "Load JSON: id=${{ matrix.test_case.id }}, smoke=${{ matrix.test_case.smoke
      }}"
    uses: ./.github/workflows/test-load-json.yaml
    with:
      path: .github/rulesets/toy-ruleset.json
      compact: ${{ matrix.test_case.compact }}
      smoke: ${{ matrix.test_case.smoke }}
      expected_name: ${{ matrix.test_case.expected_name }}
      expected_ref: ${{ matrix.test_case.expected_ref }}
    secrets: inherit
