---
name: Smoke Test Release Branch Ruleset Workflow
on:
  workflow_dispatch:
    inputs:
      ruleset_path:
        description: "the path to the ruleset json"
        required: true
        type: string
        default: "./.github/rulesets/branch-release.json"
  workflow_call:
    inputs:
      json:
        description: "Release Branch Ruleset JSON body."
        required: true
        type: string
      ruleset_name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      CI_ADMIN:
        required: true
jobs:
  load-json:
    name: Load Ruleset JSON
    runs-on: ubuntu-latest
    outputs:
      # forward inputs if workflow_call, else load-json
      json: ${{ inputs.json || steps.load-json.outputs.json }}
      ruleset_name: ${{  inputs.ruleset_name || steps.load-json.outputs.ruleset_name
        }}
    steps:
      - if: ${{ ! inputs.json }}
        uses: actions/checkout@v4
      - name: Load production ruleset
        if: ${{ ! inputs.json }}
        id: load-json
        uses: ./.github/actions/load-json
        with:
          path: ${{ inputs.ruleset_path }}
          smoke: true
  core-upsert-ruleset:
    name: Post Smoked Ruleset
    needs: load-json
    uses: ./.github/workflows/core-upsert-ruleset.yaml
    with:
      json: ${{ needs.load-json.outputs.json }}
      ruleset_name: ${{ needs.load-json.outputs.ruleset_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
      CI_ADMIN: ${{ secrets.CI_ADMIN }}
  core-validate-ruleset:
    needs: [load-json, core-upsert-ruleset]
    uses: ./.github/workflows/core-validate-ruleset.yaml
    with:
      expected_json: ${{ needs.load-json.outputs.json }}
      ruleset_id: ${{ needs.core-upsert-ruleset.outputs.ruleset_id }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
      CI_ADMIN: ${{ secrets.CI_ADMIN }}
  cleanup-smoked-ruleset:
    needs: [core-upsert-ruleset, core-validate-ruleset]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove smoke ruleset
        uses: ./.github/actions/github-rest-api
        with:
          method: DELETE
          endpoint: /repos/${{ github.repository }}/rulesets/${{ needs.core-upsert-ruleset.outputs.ruleset_id
            }}
          token: ${{ secrets.CI_ADMIN }}
